# This is a basic workflow to help you get started with Actions

name: pull images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
            description: '原镜像名称:版本'
            required: true
            default: 'redis:6.2.5'
      NEW_NAME:
            description: '同步后镜像名称:版本'
            required: true
            default: 'redis:6.2.5'
      TARGET_REGISTRY:
            description: '仓库地址'
            required: true
            default: 'crpi-4pzeonk5t25gtoqn.cn-hangzhou.personal.cr.aliyuncs.com/thmguai/images'
      TARGET_REPOSITORY:
            description: '命名空间'
            required: true
            default: 'thmguai'
      TARGET_DOCKRE_REGISTRY:
            description: '镜像仓库'
            required: true
            default: 'images'
      ARCH:
            description: '系统架构'
            required: true
            default: 'amd64'
            type: choice
            options:
              - amd64
              - arm64
              - arm/v7
              - arm/v6
              - '386'
              - s390x
              - ppc64le
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
